name: Deploy to Firebase

on:
  push:
    branches: [ main ]

env:
  REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.SONAR_TOKEN }}'  # Only needed if using SonarCloud
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'  # Required
          projectId: your-project-id  # Replace with your actual Firebase project ID
          channelId: live  # Optional: For preview channels
